# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='parent',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('S', 'Staff'), ('P', 'Parent')], max_length=1),
        ),
    ]
