# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20161104_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='Day',
        ),
    ]
