# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20161104_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='checkin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='checkout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
