# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20161104_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkin.Child'),
            preserve_default=False,
        ),
    ]
