# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_day_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='on_site',
            field=models.BooleanField(default=True),
        ),
    ]
