# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_child_on_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='on_site',
        ),
    ]
