# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_day_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
